### ISSUE TITLE
Boot process hangs sometimes (Possible deadlock?)

### ISSUE THREAD

**Issue by athei** [vit9696/AppleALC#75] opened 2016-08-13 10:31 UTC
I use AppleALC since Sierra PB3 through PB4 so I can not speak for earlier versions. I use this commit since the latest release had kernel panics on sierra: d21d436c9a78ce291c960c61f8901c613213812a

What I experience is that some times the boot just hangs (apple logo / stalling progress bar). Then I have to hard reset and try again. Then it works (most of the time). It happens mostly when I start the Hackintosh for the first time at that day (cold start / no reboot). Some times it does not work multiple times after another then I try booting without caches or just verbose mode, which resolves the issue. When I remove AppleALC the problem does not appear.

You added some locks  in the latest patches. My guess without looking too hard at the code is that you probably introduced a race condition resulting in a deadlock under the wrong circumstances.

This makes sense because locks are notorious for introducing deadlocks and changing the timing (verbose mode, no caches) resolves the issue.

**Comment by vit9696** [comment] 2016-08-13 12:18
Hi,

Unfortunately the issue is much deeper than you might think. That's not me but Apple introduced a dead lock in Sierra, [right here](https://github.com/vit9696/AppleALC/blob/master/Common/kern_patcher.cpp#L390). It assumes that the callback runs very quickly and acquires a memory allocation lock right afterwards. However, an interrupt is generated and the lock is acquired in the other place locking the boot process forever.

My initial idea was to disable interrupts, however, due to XNU specifics they could have gotten reenabled at certain places, and disabling them led to malfunctioning of certain parts of code.

My second idea was to acquire the memory allocation lock itself and avoid allocating any memory myself. However, the IOReg APIs I use do that, and to let them function I need to release the lock. 

There clearly is a race-condition here, in fact three, and I am aware of all. First the initial one between lock acquisition in the beginning of my callback, and an interrupt. Second one between interrupts and lock releases allowing memory allocations to succeed. Third one between the release of the lock in my handler, and an acquisition of it later right outside in XNU.

The first one should not happen in a way it does not normally happen without AppleALC, the timing is basically the same, and even though that code is deadly Apple relies on it. The third one can be fixed by nopping upstream lock instructions and not releasing the lock itself. 

The second one is worst, and it might be the one you have trouble with, I initially forgot about those APIs allocating memory, and calling them before is not possible because they use the results of probing performed by AppleHDAController (and because IORegistry is not even filled earlier).

You could try disabling interrupts and then enabling them in the lock releases I added for Sierra around IOReg APIs, but that will almost certainly panic since it seems to call the allocator via an interrupt. All in all it is important to know where exactly it hands, so if you have kernel debugger, it would be of some help, otherwise try to boot in -v -alcdbg mode and record the lines appearing before a hang.

**Comment by athei** [comment] 2016-08-13 12:36
Thank you for the extensive explanation. Although I have some driver development experience with Linux I can't comprehend all the things you wrote. Basically because I do not have a broad overview about how AppleALC does the kext patching.  I guess most of the callbacks and functions you are using for that you have extracted from the XNU sources because they are not included in the SDK, right? But how did you know what changes Apple did in Sierra? They did not release the sources, yet.

Does there exist some broad overview into the AppleALC code which could get other developers started? Of course I could just read the source (I have to do this anyways) but some short guide with the broad concepts used and where the caveats are would be really helpful.

I added  -v and -alcdbg to clover. Will report back when it happens again.

**Comment by vit9696** [comment] 2016-08-13 13:19
Well, in brief AppleALC installs itself to a [callback](https://github.com/vit9696/AppleALC/blob/master/Common/kern_patcher.cpp#L164) invoked after loading every kext, and when the kext matches AppleHDAController/AppleHDA (or some others) it runs a [handler)(https://github.com/vit9696/AppleALC/blob/master/AppleALC/kern_alc.cpp#L107), which solves codec controller info, codec info, patches kext memory, installs intercepting callbacks to resource loading functions. Most of the code was commented (I tried to make it easy to read) but I guess some questions may still arise.

As for Sierra specifics… as usual this was understood via some basic reverse-engineering. Several APIs used are indeed not available as public APIs, and I have to solve their addresses in memory.

I will be waiting for your report, thanks!

**Comment by athei** [comment] 2016-08-14 10:04
I tried starting with -alcdb. It did not stall while I had it enabled. I had to remove it because when it is enabled the sound is completely broken (delay and quality) and the OS is somewhat laggy. I played a game and it was as if I had very low FPS while the FPS counter said 100 fps. Is this intended?

**Comment by vit9696** [comment] 2016-08-14 12:03
-alcdbg* This is not really possible. The only cause could be -v, but that is also unlikely. AppleALC prints almost nothing to system log after booting (unless you have constant kextload/kextunload).

**Comment by athei** [comment] 2016-08-14 12:05
Okay then it was a coincidence I guess. I will add it back and report when it happens again.

**Comment by athei** [comment] 2016-08-15 09:48
Did not happen so far (right now I am booting only once a day and do not have time for extensive testing). I looked into the code and noticed that I have to compile it with "#define DEDBUG" to have the "DBGLOG" print something (in addition to adding the parameter). I guess I have to deploy a debug build to have this enabled. I will add the define in the release build to not alter the timing too much.

**Comment by athei** [comment] 2016-08-18 05:40
Okay I tried to just enable DBGLOG unconditionally instead of doing a proper Debug build. That did not work: The kext loaded but did no parching at all -> no devices 
Don't know why but it was this way (tried 3 boots always the same)

Then I did a proper debug build and got multiple hangs. All of them ended with this message being printed forever in quick succession:
"alc @ codec entry misses properties, skipping"

I could not see what was in the Log before because it fills the whole screen very quickly.

**Comment by vit9696** [comment] 2016-08-18 12:39
Mhm. That's weird. The message you get is printed when AppleALC fails to obtain [codec information](https://github.com/vit9696/AppleALC/blob/9f0f10d1a659d1e261e059f8a3d36f6c6e0b7b66/AppleALC/kern_alc.cpp#L289), i.e. IOHDACodecVendorID and IOHDACodecRevisionID. According to AppleHDA (well, its assembly), one is supposed to continue [asking IOReg](https://github.com/vit9696/AppleALC/blob/master/Common/kern_iokit.cpp#L98) for these values. Perhaps it gets not enough time to load it in a separate thread, so I could suggest you moving the locks a bit?

**Comment by athei** [comment] 2016-08-18 19:27
Shouldn't IORegistryEntry::getProperty block because it returns the value? So there is no race condition between the retrieval and the re-obtaining of the lock.

Allow me some more questions regarding the broader situation. Do you know why the memory lock acquired by the interrupt blocks the boot process? Is this some deadlock between the thread that executes the callback and later tries to acquire the lock? I mean to deadlock there must be another lock or resource that is held by the callback thread (so they wait for each other). Maybe that is the place to start.

**Comment by vit9696** [comment] 2016-08-19 04:53
> Shouldn't IORegistryEntry::getProperty block because it returns the value? So there is no race condition between the retrieval and the re-obtaining of the lock.
Ah, sorry, I might have sounded confusing. getProperty does nothing but returns the current value after obtaining it from IOReg. What I fear is that the value itself does not make its way to IOReg due to the memory allocation lock. I do not think this should be the case but given your prints in the log it is the first assumption that arises in my head.

> Do you know why the memory lock acquired by the interrupt blocks the boot process? 
It is not like I know what exactly is acquired by the interrupt. I know that kext loading stops if does not acquire memory lock quickly enough. Quite possible the interrupt has nothing to do to the memory lock I acquire but something else. My only experience with Sierra so far is a VM installation and a few hours of static disassembly. I would prefer not to speculate but so far it is likely that the whole thread is suspended and never resumed. The right way here is to set a kernel debugger up and see what actually happens. But that's the matter of time I cannot imagine myself spending on it at the moment.

**Comment by athei** [comment] 2016-08-23 13:45
I had this error now 5 times since my last posting. It was always the same message as before:

> **alc @ codec entry misses properties, skipping**

At least it is always the same error. Since it is not reproducible it is hard to check if moving the locks helps fixing the error.

**Comment by Mirone** [comment] 2016-09-15 11:15
@athei ,
 you tred this: https://clover-wiki.zetam.org/Configuration/Devices#devices_audio_audio-resethda

**Comment by athei** [comment] 2016-09-15 19:26
I did not know about it. I just added the key and will report back. Is there a way to verify that the ResetHDA is working? Did not find any key to enable logging in the clover wiki.

**Comment by vit9696** [comment] 2016-09-15 20:45
Clover debug output can be read with `bdmesg` but I do not think RestHDA actions are logged anywhere.

**Comment by athei** [comment] 2016-10-06 23:00
Okay I tested for a while and unfortunately the bug is still there. Sometimes the boot just hangs. Am I really the only one that experiences this?

**Comment by vit9696** [comment] 2016-10-07 03:46
Yes. So far you are the only one. I do really wonder whether this is an AppleALC issue. As I explained above the "freeze" is not really a freeze but just AppleALC trying to obtain the necessary codec information from IOReg. It loops for quite a while [here](https://github.com/vit9696/AppleALC/blob/master/Common/kern_iokit.cpp#L119). The max count value is really [large](https://github.com/vit9696/AppleALC/blob/master/Common/kern_iokit.hpp#L24) and for this reason it looks like a feeze.

Since the information is not there it is likely that the codec is not initialising most of the time for a weird reason. You could disable AppleALC or reduce the max count but that would not change the fact AppleHDA(Controller) is not loading (!).

Why… I do not know, perhaps your codec needs some commands from codec commander or something. Maybe it is a good idea to ask other people having the same codec? Also, if the issue is still there, why not to try VoodooHDA? Sound quality is the same, just voodoo often needs some configuration.

**Comment by pkk0** [comment] 2016-10-08 09:59
Hi,
Today I received the same error on which you discuss. I'm not sure whether panic report will be necessary, but  I will post it: 
```
*** Panic Report ***
panic(cpu 3 caller 0xffffff8000310785): "thread_invoke: preemption_level 1, possible cause: blocking while holding a spinlock, or within interrupt context"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.1.32/osfmk/kern/sched_prim.c:2077
Backtrace (CPU 3), Frame : Return Address
0xffffff911116b990 : 0xffffff80002f748c 
0xffffff911116ba10 : 0xffffff8000310785 
0xffffff911116ba90 : 0xffffff800030f4ee 
0xffffff911116bad0 : 0xffffff80004020a9 
0xffffff911116bb30 : 0xffffff800089040a 
0xffffff911116bbe0 : 0xffffff7f82d536e5 
0xffffff911116bc00 : 0xffffff7f82d490df 
0xffffff911116bca0 : 0xffffff7f82d48e92 
0xffffff911116bce0 : 0xffffff7f82d542d6 
0xffffff911116bd20 : 0xffffff800084e778 
0xffffff911116bda0 : 0xffffff8000845ee4 
0xffffff911116be10 : 0xffffff8000852c92 
0xffffff911116be60 : 0xffffff80008b6f90 
0xffffff911116be80 : 0xffffff800089b44e 
0xffffff911116bf10 : 0xffffff800089b0d6 
0xffffff911116bf60 : 0xffffff800089caee 
0xffffff911116bfb0 : 0xffffff80002a6af7 
      Kernel Extensions in backtrace:
         as.vit9696.AppleALC(1.0.16)[A2176A8D-0B84-3DEC-884D-4F94324ABD91]@0xffffff7f82d48000->0xffffff7f82e02fff
```

**Comment by vit9696** [comment] 2016-10-08 11:25
@pkk0 it is unlikely the issue is the same, your panic log without keepsyms=1 in boot-args is useless.

**Comment by pkk0** [comment] 2016-10-08 11:31
@vit9696 What keepsyms=1 flag does?

**Comment by athei** [comment] 2016-10-08 11:32
You will see the symbol names (function names) instead of their addresses in the panic log.

**Comment by vit9696** [comment] 2016-11-18 06:57
Does the issue still happen with the recent version?

**Comment by pkk0** [comment] 2016-11-18 07:25
In my case, the problem seems to be solved.

**Comment by athei** [comment] 2016-11-18 10:25
With which version? As far as I remember it also happened for 1.17 for me. Right now I removed the kext because of this problem. I can test with the next version :)

**Comment by vit9696** [comment] 2016-11-19 15:28
Latest commit probably.

**Comment by athei** [comment] 2016-11-25 13:47
I installed the latest commit 9ed485d7b5544212c5299bddee315a4e4b2c463a

It is still happening for me. I never had a panic. It's always the hang like already discussed. When it happens it's always after a coldboot and then most of the time I have to reset multiple times before it works again.

I mean we all know that there are race conditions. It's just that my hardware config has the "right" timings while others are more lucky.

**Comment by vit9696** [comment] 2016-11-25 13:49
Sigh. Pretty much expected. Anyway, we got a [source release](https://opensource.apple.com/release/os-x-1012.html) from apple, and I am somewhat hoping to understand things better now. At least once I get a little free time.

**Comment by vit9696** [comment] 2016-11-28 10:48
@athei [this commit](https://github.com/vit9696/AppleALC/commit/12d7fe07644d22b0f50bac191f48b78063ff9af7) should hopefully fix your issues. Please check it out.

**Comment by athei** [comment] 2016-11-28 11:45
Installed it! Will report back in a few days when I have enough data.

**Comment by vit9696** [comment] 2016-12-05 14:05
@athei so, may I assume it isbetter now?

**Comment by athei** [comment] 2016-12-05 14:08
Didn't had that much boots since then because I was away from home. I think approximately 10 boots without the error surfacing. So it did not happen since then bot some times the error does not surface for a while. But it is looking very promising.

**Comment by vit9696** [comment] 2016-12-05 15:04
Well then, I should probably release an update now and close this issue.
If it appears again, the cause will likely be different from the previous one, so create a new report.
Thanks.

**Closed by vit9696** 2016-12-05 15:04 UTC
