### ISSUE TITLE
Ozmosis and  AppleALC

### ISSUE THREAD

**Issue by 935713827** [vit9696/AppleALC#34] opened 2016-04-10 13:21 UTC
I don't speak English, please allow me to use Chinese

Ozmosis 引导  ，把AppleALC 放入到EFI的EFI/Oz/x**** *** *里面 无法启动 开机后 选择OSX 盘符回车 屏幕黑色  ，（但显示器是工作的）
目前正在尝试把AppleALC 转换为FFS 插入BIOS

**Comment by vit9696** [comment] 2016-04-10 13:32
Do not flash this or you won't be able to boot your computer at all!!!!!

**Comment by vit9696** [comment] 2016-04-10 13:35
Ozmosis has a bug. It cannot load PinConfigs.kext. PinConfigs.kext has no CFBundleExecutable.
To fix this you need to merge IOKitPersonalities from PinConfigs.kext to AppleALC.kext.
You may use: https://github.com/cecekpawon/AppleALC/tree/master/Extras

**Comment by 935713827** [comment] 2016-04-10 14:17
Thank you very much ，I'm going to attempt
Thank

**Comment by 935713827** [comment] 2016-04-10 14:43
When I tested the 'PinConfigs' and 'AppleALC' were converted into FFS insert BIOS
Is it correct

**Comment by vit9696** [comment] 2016-04-10 14:45
Hardly matters where to put AppleALC. You may put them to EFI and BIOS.
However, Ozmosis won't boot if you have standalone PinConfigs in use. You may only use merged kexts with Ozmosis.

**Comment by 935713827** [comment] 2016-04-10 15:05
tomorrow I will put the issue I have encountered in the  post to tell more people, so that those who use the Ozmosis can normally use your AppleALC

thank you

good night 

I have to go to sleep
Bey Bey

**Comment by Aleric** [comment] 2016-04-15 12:42
thank you for your work and  can you help me fix my computer (lenovo Y50-70 ISE)'s Realtek alc283 ? this project don't work in my realtek alc283 but i don't know how to fix it.thanks.

**Comment by vandroiy2013** [comment] 2016-04-15 12:49
How can we help if we don't know what you have done. Check steps to run appleALC. 

1. Your AppleHDA.kext MUST be clean (vanilla)
2. HDEF section in your DSDT (or clover fix FixHDA_8000->True)
3. Layout-id specified in your DSDT (or clover Audio->Inject) 
4. Remove ALL patches for audio from your config.plist KextsToPatch
5. Remove DummyHDA.kext from S/L/E (if exists)
6. Remove VoodooHDA.kext and AppleHDADisabler.kext (if exists)
7. Intel HDMI Audio on HD4000/HD4600 - use clover key UseIntelHDMI->True 

Provide DarwinDumper & IORegistryExplorer reports.

**Comment by vit9696** [comment] 2016-09-09 12:39
Since Ozmosis is [discontinued](http://www.insanelymac.com/forum/topic/285920-new-os-x-compatible-motherboard-quo/?p=2272173) and since a workaround does [exist](https://github.com/vit9696/AppleALC/blob/master/Tools/merge_pinconfigs.sh) the issue is invalid and therefore closed.

**Closed by vit9696** 2016-09-09 12:39 UTC
