### ISSUE TITLE
Code signing problem

### ISSUE THREAD

**Issue by cecekpawon** [vit9696/AppleALC#18] opened 2016-03-14 02:30 UTC
Had to do this with last commit to successfully compile after changing "`PinConfigs.kext`"

![1](https://cloud.githubusercontent.com/assets/8464050/13733557/ef7f2646-e9c6-11e5-85fc-9b4d24e54dca.png)

Xcode Version 6.1.1 (6A2008a) / os 10.11.4

```
CodeSign /Users/xx/Library/Developer/Xcode/DerivedData/AppleALC-cxetzedgwdwlqnddiiyrzseszyru/Build/Products/Release/AppleALC.kext/Contents/PlugIns/PinConfigs.kext
    cd /Volumes/xx/AppleALC
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,resource-rules /Users/xx/Library/Developer/Xcode/DerivedData/AppleALC-cxetzedgwdwlqnddiiyrzseszyru/Build/Products/Release/AppleALC.kext/Contents/PlugIns/PinConfigs.kext

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/xx/Library/Developer/Xcode/DerivedData/AppleALC-cxetzedgwdwlqnddiiyrzseszyru/Build/Products/Release/AppleALC.kext/Contents/PlugIns/PinConfigs.kext: unsealed contents present in the bundle root
Command /usr/bin/codesign failed with exit code 1
```

Edit: Only happen when i git clone this project under terminal / github desktop (GUI). Direct download "zip" file is OK.

**Comment by vit9696** [comment] 2016-03-14 04:28
Not reproducible. Retry with a **recent** Xcode version already, you are not on 10.9 to require something that ancient.

**Comment by cecekpawon** [comment] 2016-03-14 04:41
Yeah @vit9696 thanks, ill update my xcode soon. As i said, problems are gone when i just download master branch as a zip, trying with svn export now. Maybe you want to take a look this [project](https://github.com/Mieze/IntelMausiEthernet) (they dont need to code sign as we are running from bootloader), are we?

**Comment by vit9696** [comment] 2016-03-14 04:46
@cecekpawo well, I can replace - with "Don't codesign", but won't it make kext unloadable on Mavericks and above (even with SIP off/kext-dev-mode)?

**Comment by cecekpawon** [comment] 2016-03-14 04:53
Cannot guarantee that will work <10.10, since i dont have other os ver to test. I guess you need more volunteers to give a test. They [claimed](http://www.insanelymac.com/forum/files/file/396-intelmausiethernet/) to run with 10.9 btw

**Comment by vit9696** [comment] 2016-03-14 04:56
Well, I think it is not so important to check something new, since as is it builds and runs with Xcode 6.2 on 10.9 (latest ver there) and Xcode 7.2.1 on 10.11 (latest ver here). No need to deal with 6.1.1 issues in my opinion, especially when they can be fixed by the users themselves if really needed. 

Reopen if you have issues with Xcode 7.2.1 :)

**Closed by vit9696** 2016-03-14 04:56 UTC

**Comment by cecekpawon** [comment] 2016-03-14 06:31
:smile_cat: just let you know, removing ```._*``` from ```PinConfigs.kext``` fix my issues.. Please re-close this, thank you!
